#!/bin/sh
if [ -z "$SCM_METRICS_VERSION" ]; then
	/usr/lib/metrics/.env/bin/pip install --upgrade SDH-SCM-Metrics
else
	/usr/lib/agora/.env/bin/pip install --upgrade SDH-SCM-Metrics==$SCM_METRICS_VERSION
fi

/usr/lib/agora/.env/bin/sdh-scm-metrics &
